package fr.xgouchet.chronorg.triplea.generator

import com.squareup.kotlinpoet.ClassName
import fr.xgouchet.chronorg.triplea.TripleA

object TripleAPoet {

    const val SUFFIX_ACTIVITY = "Activity"
    const val SUFFIX_FRAGMENT = "Fragment"
    const val SUFFIX_ADAPTER = "Adapter"
    const val SUFFIX_PAGERADAPTER = "PagerAdapter"
    const val SUFFIX_VIEWHOLDER = "ViewHolder"
    const val SUFFIX_DATASOURCE = "DataSource"

    const val SUFFIX_CONTRACT = "Contract"
    const val SUFFIX_PRESENTER = "Presenter"
    const val SUFFIX_VIEW = "View"

    const val HEADER_DISCLAIMER =
            """
 ———————————— DO NOT EDIT THIS FILE ———————————
| Generated by TripleA Plugin                  |
| TripleA project by Xavier F. Gouchet, 2018   |
| https://github.com/xgouchet/TripleA          |
 ——————————————————————————————————————————————
 """



    val DATASOURCE = ClassName.bestGuess(TripleA.Core.Source.DataSource.CANONICAL_NAME)

    val CONTRACT_VIEW = ClassName.bestGuess(TripleA.Core.Front.MVP.BaseContract.View.CANONICAL_NAME)
    val CONTRACT_PRESENTER = ClassName.bestGuess(TripleA.Core.Front.MVP.BaseContract.Presenter.CANONICAL_NAME)

    val LISTCONTRACT_VIEW = ClassName.bestGuess(TripleA.Core.Front.MVP.BaseListContract.View.CANONICAL_NAME)
    val LISTCONTRACT_PRESENTER = ClassName.bestGuess(TripleA.Core.Front.MVP.BaseListContract.Presenter.CANONICAL_NAME)

    val PAGERADAPTER = ClassName.bestGuess(TripleA.Core.Front.MVP.BaseViewPagerAdapter.CANONICAL_NAME)

    val R = ClassName.bestGuess(TripleA.Core.R)


    object Kotlin {
        val ARRAY = ClassName.bestGuess("kotlin.Array")
        val LIST = ClassName.bestGuess("kotlin.collections.List")
        val MUTABLELIST = ClassName.bestGuess("kotlin.collections.MutableList")
        val THROWABLE = ClassName.bestGuess("kotlin.Throwable")
    }


    object Android {

        val ACTIVITY = ClassName.bestGuess("android.app.Activity")
        val VIEW = ClassName.bestGuess("android.view.View")
        val VIEWGROUP = ClassName.bestGuess("android.view.ViewGroup")
        val LAYOUTINFLATER = ClassName.bestGuess("android.view.LayoutInflater")
        val INTENT = ClassName.bestGuess("android.content.Intent")

        object Support {
            val RECYCLERVIEW = ClassName.bestGuess("android.support.v7.widget.RecyclerView")
            val LINEARLAYOUTMGR = ClassName.bestGuess("android.support.v7.widget.LinearLayoutManager")
            val DIFFUTIL = ClassName.bestGuess("android.support.v7.util.DiffUtil")
            val DIFFUTIL_CALLBACK = DIFFUTIL.nestedClass("Callback")
            val SNACKBAR = ClassName.bestGuess("android.support.design.widget.Snackbar")
            val LAYOUTRES = ClassName.bestGuess("android.support.annotation.LayoutRes")
            val STRINGRES = ClassName.bestGuess("android.support.annotation.StringRes")
            val FRAGMENT = ClassName.bestGuess("android.support.v4.app.Fragment")
            val SWIPEREFRESHLAYOUT = ClassName.bestGuess("android.support.v4.widget.SwipeRefreshLayout")
            val FRAGMENTMGR = ClassName.bestGuess("android.support.v4.app.FragmentManager")
        }

        val VIEWDATABINDING = ClassName.bestGuess("android.databinding.ViewDataBinding")
    }

}